### ISSUE TITLE
In 2022-12, AspectJ Maven projects are not imported correctly anymore

### ISSUE THREAD

**Issue by kriegaex** [joker1/m2eclipse-ajdt#3]
See https://github.com/eclipse/org.aspectj/issues/223. Please take a look, this is a real blocker.

Being a Tycho and PDE noob, for the life of me I cannot get the project in my fork compiling locally with Maven and Tycho, even though I tried to upgrade the Eclipse repo and a few other things. But my local build always fails, even against an AJDT copy depending on 2022-12 JDT classes.

**Comment by joker1** [comment]
I may look into this issue when I have time. I am personally experiencing issues with AJDT compile too.

**Comment by kriegaex** [comment]
I am on it. Maybe I create a PR, but I am not sure if it will be a good one.

**Comment by kriegaex** [comment]
@joker1, can you please also install the developer builds of
  * m2eclipse-ajdt,
  * AJDT

in order to test if those two changes combined solve the problem for you? For me it looks OK.
